# Site settings
title: Chong's Blog
email: chong.he07@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Enjoy operation system, linux kernel, dedicate to wireless development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ChongHe07
github_username:  3p14

# Build settings
markdown: kramdown
